### ISSUE TITLE
Questions Regarding KV Cache Dimensions

### ISSUE THREAD

**Issue by ydyhello** [Infini-AI-Lab/MagicPIG#1]
Thanks for your great work! 
Could you please explain why, when the KV cache is ready in the CPU memory, you reshape the original 4-dimensional shape `[self.batch_size, self.num_key_value_heads, -1, self.head_dim]` into a 3-dimensional shape `[self.batch_size * self.num_key_value_heads, -1, self.head_dim]`? Is there any benefit to doing so? Thank you in advance for your explanation.

```
        self.k_cache :list[torch.Tensor] = [torch.zeros(
            batch_size * config.num_key_value_heads,
            max_length,
            config.hidden_size // config.num_attention_heads,
            device="cpu",
            dtype=self.dtype
        ) for _ in range(config.num_hidden_layers)]

        self.v_cache :list[torch.Tensor]= [torch.zeros(
            batch_size *config.num_key_value_heads,
            max_length,
            config.hidden_size // config.num_attention_heads,
            device="cpu",
            dtype=self.dtype
        ) for _ in range(config.num_hidden_layers)]
```

**Comment by dreaming-panda** [comment]
Thank you for the question. I did this reshaping mainly to create a more apparent parallelism pattern in CPUs (i.e., how to schedule open-mp threads given that each head may have different workloads). This part is not presented in this project now, and we are preparing for it now.

**Comment by ydyhello** [comment]
> Thank you for the question. I did this reshaping mainly to create a more apparent parallelism pattern in CPUs (i.e., how to schedule open-mp threads given that each head may have different workloads). This part is not presented in this project now, and we are preparing for it now.

Thank you very much for your answer! I also have a question to ask. Why did you set your max_length to `GEN_LEN + PREFIX_LEN + 128`? Does the number 128 have any special meaning?

```
llm = LLMEngine(MODEL_NAME, 1, GEN_LEN + PREFIX_LEN + 128, DEVICE, DTYPE, config)
```

**Comment by dreaming-panda** [comment]
No, it does not have a special meaning.  I will clean the code in the next release.

Thank you for your interest!!
